### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by adhil-bit** [mrafiqk/html-pdf-node#105]
0|admin  | Error: Failed to launch the browser process!
0|admin  | /home/ubuntu/admin.dummy.com/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
0|admin  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|admin  |     at onClose (/home/ubuntu/admin.dummy.com/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
0|admin  |     at Interface.<anonymous> (/home/ubuntu/admin.dummy.com/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
0|admin  |     at Interface.emit (node:events:526:35)
0|admin  |     at Interface.emit (node:domain:489:12)
0|admin  |     at Interface.close (node:internal/readline/interface:533:10)
0|admin  |     at Socket.onend (node:internal/readline/interface:259:10)
0|admin  |     at Socket.emit (node:events:526:35)
0|admin  |     at Socket.emit (node:domain:489:12)
0|admin  |     at endReadableNT (node:internal/streams/readable:1359:12)
0|admin  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

not generating pdf ? puppeter depednecy expired ..any solution to fix it?

**Comment by EmmanDizon** [comment]
up

**Comment by adhil-bit** [comment]
> up

hi bro is it working now? i just used puppeteer - where i need to install browser in server...

**Comment by lmm1ng** [comment]
up

**Comment by jonab12** [comment]
Possible solution for AWS EC2 Ubuntu 20.04.6

I was missing libgbm.so.1

```
sudo apt-get update
sudo apt-get install -y libgbm-dev
```
If this does not work for you check if any of the packages below are missing or out of date:

```
ca-certificates
fonts-liberation
libasound2
libatk-bridge2.0-0
libatk1.0-0
libc6
libcairo2
libcups2
libdbus-1-3
libexpat1
libfontconfig1
libgbm1
libgcc1
libglib2.0-0
libgtk-3-0
libnspr4
libnss3
libpango-1.0-0
libpangocairo-1.0-0
libstdc++6
libx11-6
libx11-xcb1
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxss1
libxtst6
lsb-release
wget
xdg-utils
```
